// Code generated by mockery v2.30.1. DO NOT EDIT.

package mongo

import (
	elastic_go_app_cleancodemongo "github.com/RajathSVasisth/elastic-go-app-cleancode/mongo"
	mock "github.com/stretchr/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *Database) Client() elastic_go_app_cleancodemongo.Client {
	ret := _m.Called()

	var r0 elastic_go_app_cleancodemongo.Client
	if rf, ok := ret.Get(0).(func() elastic_go_app_cleancodemongo.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elastic_go_app_cleancodemongo.Client)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: _a0
func (_m *Database) Collection(_a0 string) elastic_go_app_cleancodemongo.Collection {
	ret := _m.Called(_a0)

	var r0 elastic_go_app_cleancodemongo.Collection
	if rf, ok := ret.Get(0).(func(string) elastic_go_app_cleancodemongo.Collection); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elastic_go_app_cleancodemongo.Collection)
		}
	}

	return r0
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
